---
name: Francois 
surname: du Toit
position: "PhD Candidate"
address: "University of British Columbia, Vancouver"
profilepic: "./img/me.jpg"
phone: +778 919 5353
email: "fdutoit2009@gmail.com"
#github: francoisdt14
#twitter: 
linkedin: francoisdt14
orcid: 0000-0002-6637-7041
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
docname: CV
output: vitae::awesomecv
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)


pkgs <- c('vitae' ,'here' ,'tinytex' ,'tibble' ,'glue' ,'rmarkdown' ,'dplyr', 'readr' ,'yaml')
xfun::pkg_attach2(pkgs)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data sctructure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative Filepaths
             ,'readr'     # Data Loading
             ,'tidyverse' # Needed for bind_rows and whatever
             ,'scholar'   # Updating publications from google scholar
             ,'kableExtra'# Adding technicalskills table
            )
library(magrittr)
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
lapply(packages, library, character.only = TRUE) %>%
  invisible()

source(file = here("r","data.r"))

```

# Education

```{r EDUCATION}

education %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

# Experience

```{r Experience, results = "asis"}

experience %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

# Teaching

```{r TeachingExperience}

teachingExperience %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

# Skills

```{r TechnicalSkills}

skills %>%
  detailed_entries(
    with = area,
    what = skills,
  )

```

# Awards

```{r AWARDS}

awards %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = glue::glue("{firstYear} {secondYear}",.na = ""),
    where = where
  )

```

# Peer-Reviewed Publications

```{r Publications}
bib <- bibliography_entries("publications.bib") %>%
  arrange(desc(issued))

bib$`container-title` <- str_to_sentence(bib$`container-title`, locale = "en")

bib
  
```

# Presentations

```{r PRESENTATIONS}

presentations %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear}",.na = ""),
    where = where, .protect = F
  )

```

# Activities

```{r Activities}

activities %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

